version: "3.8"
services:
  casaapp:
    build: .
    image: casaapp:dev
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    environment:
      EXPO_DEBUG: "true"
    restart: unless-stopped
    # network_mode: "host"   # abilita SOLO su Linux se vuoi usare --lan

volumes:
  node_modules: